name: Track Repo Activity

on:
  push: # Trigger on any push to any repository
    branches:
      - "*" # Track all branches in the repository

jobs:
  track_activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Fetch Commit Data
        run: |
          echo "### Commit Log - $(date)" >> README.md
          echo "- Repository: ${{ github.repository }}" >> README.md
          echo "- Branch: ${{ github.ref }}" >> README.md
          echo "- Commit Message: ${{ github.event.head_commit.message }}" >> README.md
          echo "- Commit URL: ${{ github.event.head_commit.url }}" >> README.md
          echo "" >> README.md

      - name: Commit and push the updated log
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated Activity Log with new commit details"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
